### ISSUE TITLE
nano crashes on any keypress

### ISSUE THREAD

**Issue by nonchip** [OpenPrograms/gamax92-Programs#6]
because of a in nil-call in line 703 (`keys[code]:sub`) and (after replacing with `string.sub(keys[code],...)`) 708 because `keys[code]` is non-string, maybe the event api got changed?

my OC version: 1.7.0 running LuaROM + OpenOS

**Comment by gamax92** [comment]
What program of mine is this bug report supposed to be for? There's a lot of stuff in this repository.

**Comment by nonchip** [comment]
oh fail, sorry, clicked right from the code file into the issues, and forgot how many programs there are :P
talking about nano (which would be SO great to have, because edit sucks :P)

**Comment by gamax92** [comment]
Ahh, the nano clone here is a bit old and featureless but I'll look into it.

**Comment by nonchip** [comment]
I'm just getting started with OC, but I know a fair bit of lua, so if I can be of any more help please ask :)
dunno really much about the api though :/

**Comment by gamax92** [comment]
This turned out to be a bug in OpenOS, and has been corrected in 
https://github.com/MightyPirates/OpenComputers/commit/43a4db05ecc12356070aaf5e0260d8a120783ba4

The latest version of OpenComputers can be grabbed from http://ci.cil.li/view/OpenComputers/, or manually apply the above commit to your version of OpenOS if you'd like to try out nano.

**Comment by nonchip** [comment]
thanks for getting back to me on this, I'll try it :)
